### ISSUE TITLE
Credit Card Transactions Not Captured

### ISSUE THREAD

**Issue by grid8** [fdarveau/wealthsimple-export-transactions#6]
I noticed you mentioned you would update it with any missing transaction types it wasn't capturing, looks like it doesn't capture anything for the Credit Card product. Would be appreciated if you could update it. 

Appreciate the efforts.

**Comment by fdarveau** [comment]
Yes, I will update this script as I encounter new transaction types. Since I don't have the credit card, I have no idea what the associated transaction types are.

I can add support for transaction types you need if you provide transaction details (don't forget to anonymize any personal data such as account number, merchant, transaction amount, etc.) found in the browser console after trying to export them, along with the label shown on the WealthSimple website for each currently unsupported transaction type to add as a description in the generated file.

**Comment by grid8** [comment]
Appreciate it, looks like the following are missing, let me know if you need anything else. 

Missing Transactions

Credit Card

[CREDIT_CARD/PURCHASE] - (Purchase)
[CREDIT_CARD/PAYMENT] - (Payment)
[CREDIT_CARD/REFUND] - (Refund)
[CREDIT_CARD/CASH_WITHDRAWAL] - (Cash Withdrawal)
[CREDIT_CARD/INTEREST] - (Interest charge)

Chequing

[DEPOSIT/CHEQUE] - (Cheque deposit)
[CREDIT_CARD_PAYMENT] - (Credit card payment)
[WITHDRAWAL/CHEQUE] - (Cheque withdrawal)
[WITHDRAWAL/CROSS_BORDER] - (International transfer)
[REIMBURSEMENT/REWARD] - (Cash back) (Appears to be a legacy name)
[REIMBURSEMENT/CASHBACK] - (Cash back)
[PROMOTION/INCENTIVE_BONUS] - (Promotional bonus)

**Comment by fdarveau** [comment]
If you can provide the complete object found in the browser console (with anonymized data) for each transaction type, it would be helpful. It would allow me to make sure the payee and description have all the info available (ex : there may be extra info about the deposited/withdrawn cheque such as its number). There may be new properties for those new transaction types that the script does not look for yet.

**Comment by fdarveau** [comment]
I pushed a partial update to this branch : https://github.com/fdarveau/wealthsimple-export-transactions/blob/add-credit-card-transations/wealthsimple-export-transactions-csv.user.js.

Some texts (mostly payees) are placeholders using properties I expect data to be in based on other transaction types or the same text as the notes until I can validate the actual properties content based on your full (anonymized) browser console log or until I get access to the credit card and encounter these transaction types myself.

**Comment by grid8** [comment]
REDACTED

**Comment by fdarveau** [comment]
Thanks for providing this! I was able to add the cheque number as I expected, and also more information for international transfers.

I updated the script in this branch : https://github.com/fdarveau/wealthsimple-export-transactions/blob/add-credit-card-transations/wealthsimple-export-transactions-csv.user.js

Let me know if you encounter any issue.

If everything looks good on your end, I will merge the changes into the main branch.

**Comment by grid8** [comment]
Much appreciated, will test and report back if anything pops up.

**Comment by grid8** [comment]
I missed one for Chequing, otherwise so far all looks good for Chequing. Unfortunately I'm still not getting anything for Credit Card exports. Unsure why, I don't see any errors in the console. The file export however is named as following. "Wealthsimple Unknown Transactions up to 2025-10-15"

[REIMBURSEMENT/ATM]
{
   REDACTED
}

**Comment by fdarveau** [comment]
I just pushed a new version with missing transaction types, including the ATM fees reimbursements. It also fixes the generated file name. It should now mention "Credit card" instead of "Unknown".

I will try to find out possible reasons why there is no data generated when I have some more free time and possibly ask for more information on your end, but it is hard to debug without my own credit card account, so it might take a while.

**Comment by grid8** [comment]
Thanks. It seems to export the first 1/2 transactions and that's it.

**Comment by fdarveau** [comment]
I identified an issue with exporting special characters. The issue I encountered was with the `#` symbol, but it may also fix other characters.

Can you try [this updated version](https://github.com/fdarveau/wealthsimple-export-transactions/blob/add-credit-card-transations/wealthsimple-export-transactions-csv.user.js) and let me know if all data is now exported on your end as well?

**Comment by grid8** [comment]
Tested and so far so good, I'm getting what looks like a full export. Haven't gone line by line to confirm yet but it looks promising. Much appreciated.

**Comment by fdarveau** [comment]
I merged the updated script into the main branch. I also bumped the version so you should be able to check for updates in your script add-on and detect it. You can also update it manually in case it doesn't work.

You can also remove the data you provided me in the earlier comment if you want.

If you encounter any problem, feel free to open a new issue.
